name: Build & Test PR

on:
  pull_request:
    branches: [ main ]

env:
    PROJECT_NAME: Blazored.FluentValidation
    NETCORE_VERSION: '8.0.x'

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setting up .NET SDK ${{ env.NETCORE_VERSION }}...
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.NETCORE_VERSION }}

    - name: Restoring packages...
      run: dotnet restore

    - name: Building project...
      run: dotnet build --configuration Release --no-restore src/$PROJECT_NAME/$PROJECT_NAME.csproj